##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Pavucontrol floating
windowrule {
  name = pavucontrol-float
  match:class = org.pulseaudio.pavucontrol
  float = on
  size = 600 600
  center = on
  pin = on
}

# Blueman Manager
windowrule {
  name = blueman-float
  match:class = blueman-manager
  float = on
  size = 600 600
  center = on
}

# GNOME Calculator
windowrule {
  name = calculator-float
  match:class = org.gnome.Calculator
  float = on
  size = 500 500
  center = on
}

# Network Manager
windowrule {
  name = nm-editor-float
  match:class = nm-connection-editor
  float = on
  size = 600 600
  center = on
}

# WhatsApp Web (Chrome)
windowrule {
  name = whatsapp web
  match:class = Google-chrome
  match:title = WhatsApp Web
  float = on
  size = 1000 1000
  center = on
}

# VS Code Opacity
windowrule {
  name = vscode-opacity
  match:class = ^(Code)$
  opacity = 0.9
}

# SwayNC Blur
layerrule {
  name = swaync-blur
  match:namespace = swaync-control-center
  blur = on
  blur_popups = on
  ignore_alpha = 0
}

# Blur nwg-drawer
layerrule {
  name = nwg-drawer-blur
  match:namespace = nwg-drawer
  blur = on
}
